/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE401_Memory_Leak__char_calloc_01_good();");
	CWE401_Memory_Leak__char_calloc_01_good();


	printLine("Calling CWE401_Memory_Leak__char_calloc_22_good();");
	CWE401_Memory_Leak__char_calloc_22_good();


	printLine("Calling CWE401_Memory_Leak__char_malloc_01_good();");
	CWE401_Memory_Leak__char_malloc_01_good();

	printLine("Calling CWE401_Memory_Leak__char_malloc_02_good();");
	CWE401_Memory_Leak__char_malloc_02_good();


	printLine("Calling CWE401_Memory_Leak__char_realloc_01_good();");
	CWE401_Memory_Leak__char_realloc_01_good();

	printLine("Calling CWE401_Memory_Leak__char_realloc_03_good();");
	CWE401_Memory_Leak__char_realloc_03_good();


	printLine("Calling CWE401_Memory_Leak__int64_t_calloc_01_good();");
	CWE401_Memory_Leak__int64_t_calloc_01_good();


	printLine("Calling CWE401_Memory_Leak__int64_t_calloc_04_good();");
	CWE401_Memory_Leak__int64_t_calloc_04_good();


	printLine("Calling CWE401_Memory_Leak__int64_t_malloc_01_good();");
	CWE401_Memory_Leak__int64_t_malloc_01_good();


	printLine("Calling CWE401_Memory_Leak__int64_t_malloc_05_good();");
	CWE401_Memory_Leak__int64_t_malloc_05_good();


	printLine("Calling CWE401_Memory_Leak__int64_t_realloc_01_good();");
	CWE401_Memory_Leak__int64_t_realloc_01_good();


	printLine("Calling CWE401_Memory_Leak__int64_t_realloc_06_good();");
	CWE401_Memory_Leak__int64_t_realloc_06_good();


	printLine("Calling CWE401_Memory_Leak__int_calloc_01_good();");
	CWE401_Memory_Leak__int_calloc_01_good();


	printLine("Calling CWE401_Memory_Leak__int_calloc_07_good();");
	CWE401_Memory_Leak__int_calloc_07_good();


	printLine("Calling CWE401_Memory_Leak__int_malloc_01_good();");
	CWE401_Memory_Leak__int_malloc_01_good();


	printLine("Calling CWE401_Memory_Leak__int_malloc_08_good();");
	CWE401_Memory_Leak__int_malloc_08_good();

	printLine("Calling CWE401_Memory_Leak__int_realloc_01_good();");
	CWE401_Memory_Leak__int_realloc_01_good();


	printLine("Calling CWE401_Memory_Leak__int_realloc_09_good();");
	CWE401_Memory_Leak__int_realloc_09_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_char_01_good();");
	CWE401_Memory_Leak__malloc_realloc_char_01_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_char_10_good();");
	CWE401_Memory_Leak__malloc_realloc_char_10_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int64_t_01_good();");
	CWE401_Memory_Leak__malloc_realloc_int64_t_01_good();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int64_t_11_good();");
	CWE401_Memory_Leak__malloc_realloc_int64_t_11_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int_01_good();");
	CWE401_Memory_Leak__malloc_realloc_int_01_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int_15_good();");
	CWE401_Memory_Leak__malloc_realloc_int_15_good();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_01_good();");
	CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_01_good();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_12_good();");
	CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_12_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_01_good();");
	CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_01_good();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_13_good();");
	CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_13_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_wchar_t_01_good();");
	CWE401_Memory_Leak__malloc_realloc_wchar_t_01_good();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_wchar_t_14_good();");
	CWE401_Memory_Leak__malloc_realloc_wchar_t_14_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE401_Memory_Leak__char_calloc_01_bad();");
	CWE401_Memory_Leak__char_calloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__char_calloc_22_bad();");
	CWE401_Memory_Leak__char_calloc_22_bad();


	printLine("Calling CWE401_Memory_Leak__char_malloc_01_bad();");
	CWE401_Memory_Leak__char_malloc_01_bad();

	printLine("Calling CWE401_Memory_Leak__char_malloc_02_bad();");
	CWE401_Memory_Leak__char_malloc_02_bad();


	printLine("Calling CWE401_Memory_Leak__char_realloc_01_bad();");
	CWE401_Memory_Leak__char_realloc_01_bad();

	printLine("Calling CWE401_Memory_Leak__char_realloc_03_bad();");
	CWE401_Memory_Leak__char_realloc_03_bad();


	printLine("Calling CWE401_Memory_Leak__int64_t_calloc_01_bad();");
	CWE401_Memory_Leak__int64_t_calloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__int64_t_calloc_04_bad();");
	CWE401_Memory_Leak__int64_t_calloc_04_bad();


	printLine("Calling CWE401_Memory_Leak__int64_t_malloc_01_bad();");
	CWE401_Memory_Leak__int64_t_malloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__int64_t_malloc_05_bad();");
	CWE401_Memory_Leak__int64_t_malloc_05_bad();


	printLine("Calling CWE401_Memory_Leak__int64_t_realloc_01_bad();");
	CWE401_Memory_Leak__int64_t_realloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__int64_t_realloc_06_bad();");
	CWE401_Memory_Leak__int64_t_realloc_06_bad();


	printLine("Calling CWE401_Memory_Leak__int_calloc_01_bad();");
	CWE401_Memory_Leak__int_calloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__int_calloc_07_bad();");
	CWE401_Memory_Leak__int_calloc_07_bad();


	printLine("Calling CWE401_Memory_Leak__int_malloc_01_bad();");
	CWE401_Memory_Leak__int_malloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__int_malloc_08_bad();");
	CWE401_Memory_Leak__int_malloc_08_bad();

	printLine("Calling CWE401_Memory_Leak__int_realloc_01_bad();");
	CWE401_Memory_Leak__int_realloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__int_realloc_09_bad();");
	CWE401_Memory_Leak__int_realloc_09_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_char_01_bad();");
	CWE401_Memory_Leak__malloc_realloc_char_01_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_char_10_bad();");
	CWE401_Memory_Leak__malloc_realloc_char_10_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int64_t_01_bad();");
	CWE401_Memory_Leak__malloc_realloc_int64_t_01_bad();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int64_t_11_bad();");
	CWE401_Memory_Leak__malloc_realloc_int64_t_11_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int_01_bad();");
	CWE401_Memory_Leak__malloc_realloc_int_01_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_int_15_bad();");
	CWE401_Memory_Leak__malloc_realloc_int_15_bad();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_01_bad();");
	CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_01_bad();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_12_bad();");
	CWE401_Memory_Leak__malloc_realloc_struct_twoIntsStruct_12_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_01_bad();");
	CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_01_bad();

	printLine("Calling CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_13_bad();");
	CWE401_Memory_Leak__malloc_realloc_twoIntsStruct_13_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_wchar_t_01_bad();");
	CWE401_Memory_Leak__malloc_realloc_wchar_t_01_bad();


	printLine("Calling CWE401_Memory_Leak__malloc_realloc_wchar_t_14_bad();");
	CWE401_Memory_Leak__malloc_realloc_wchar_t_14_bad();
#endif /* OMITBAD */

	return 0;

} 
