/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE416_Use_After_Free__malloc_free_char_01_good();");
	CWE416_Use_After_Free__malloc_free_char_01_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_char_04_good();");
	CWE416_Use_After_Free__malloc_free_char_04_good();

	printLine("Calling CWE416_Use_After_Free__malloc_free_int64_t_01_good();");
	CWE416_Use_After_Free__malloc_free_int64_t_01_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_int64_t_04_good();");
	CWE416_Use_After_Free__malloc_free_int64_t_04_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_int_01_good();");
	CWE416_Use_After_Free__malloc_free_int_01_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_int_04_good();");
	CWE416_Use_After_Free__malloc_free_int_04_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_long_01_good();");
	CWE416_Use_After_Free__malloc_free_long_01_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_long_04_good();");
	CWE416_Use_After_Free__malloc_free_long_04_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_struct_01_good();");
	CWE416_Use_After_Free__malloc_free_struct_01_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_struct_04_good();");
	CWE416_Use_After_Free__malloc_free_struct_04_good();


	printLine("Calling CWE416_Use_After_Free__malloc_free_wchar_t_01_good();");
	CWE416_Use_After_Free__malloc_free_wchar_t_01_good();


	printLine("Calling CWE416_Use_After_Free__return_freed_ptr_01_good();");
	CWE416_Use_After_Free__return_freed_ptr_01_good();


	printLine("Calling CWE416_Use_After_Free__return_freed_ptr_04_good();");
	CWE416_Use_After_Free__return_freed_ptr_04_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE416_Use_After_Free__malloc_free_char_01_bad();");
	CWE416_Use_After_Free__malloc_free_char_01_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_char_04_bad();");
	CWE416_Use_After_Free__malloc_free_char_04_bad();

	printLine("Calling CWE416_Use_After_Free__malloc_free_int64_t_01_bad();");
	CWE416_Use_After_Free__malloc_free_int64_t_01_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_int64_t_04_bad();");
	CWE416_Use_After_Free__malloc_free_int64_t_04_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_int_01_bad();");
	CWE416_Use_After_Free__malloc_free_int_01_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_int_04_bad();");
	CWE416_Use_After_Free__malloc_free_int_04_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_long_01_bad();");
	CWE416_Use_After_Free__malloc_free_long_01_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_long_04_bad();");
	CWE416_Use_After_Free__malloc_free_long_04_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_struct_01_bad();");
	CWE416_Use_After_Free__malloc_free_struct_01_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_struct_04_bad();");
	CWE416_Use_After_Free__malloc_free_struct_04_bad();


	printLine("Calling CWE416_Use_After_Free__malloc_free_wchar_t_01_bad();");
	CWE416_Use_After_Free__malloc_free_wchar_t_01_bad();


	printLine("Calling CWE416_Use_After_Free__return_freed_ptr_01_bad();");
	CWE416_Use_After_Free__return_freed_ptr_01_bad();


	printLine("Calling CWE416_Use_After_Free__return_freed_ptr_04_bad();");
	CWE416_Use_After_Free__return_freed_ptr_04_bad();
#endif /* OMITBAD */

	return 0;

} 
