/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE483_Incorrect_Block_Delimitation__if_without_braces_multiple_lines_01_good();");
	CWE483_Incorrect_Block_Delimitation__if_without_braces_multiple_lines_01_good();

	printLine("Calling CWE483_Incorrect_Block_Delimitation__if_without_braces_single_line_01_good();");
	CWE483_Incorrect_Block_Delimitation__if_without_braces_single_line_01_good();

	printLine("Calling CWE483_Incorrect_Block_Delimitation__semicolon_01_good();");
	CWE483_Incorrect_Block_Delimitation__semicolon_01_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE483_Incorrect_Block_Delimitation__if_without_braces_multiple_lines_01_bad();");
	CWE483_Incorrect_Block_Delimitation__if_without_braces_multiple_lines_01_bad();

	printLine("Calling CWE483_Incorrect_Block_Delimitation__if_without_braces_single_line_01_bad();");
	CWE483_Incorrect_Block_Delimitation__if_without_braces_single_line_01_bad();

	printLine("Calling CWE483_Incorrect_Block_Delimitation__semicolon_01_bad();");
	CWE483_Incorrect_Block_Delimitation__semicolon_01_bad();


#endif /* OMITBAD */

	return 0;

} 
