/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_alloca_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_char_alloca_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_alloca_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_char_alloca_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_declare_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_char_declare_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_declare_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_char_declare_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_static_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_char_static_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_static_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_char_static_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_13_good();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_13_good();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_01_good();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_alloca_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int_alloca_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_alloca_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int_alloca_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_declare_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int_declare_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_declare_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int_declare_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_static_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int_static_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_static_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_int_static_13_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_alloca_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_long_alloca_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_alloca_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_long_alloca_13_good();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_declare_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_long_declare_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_declare_13_good();");
	CWE590_Free_Memory_Not_on_Heap__free_long_declare_13_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_alloca_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_char_alloca_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_alloca_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_char_alloca_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_declare_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_char_declare_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_declare_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_char_declare_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_static_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_char_static_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_char_static_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_char_static_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_alloca_13_bad();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_declare_13_bad();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_01_bad();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int64_t_static_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_alloca_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int_alloca_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_alloca_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int_alloca_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_declare_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int_declare_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_declare_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int_declare_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_static_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int_static_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_int_static_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_int_static_13_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_alloca_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_long_alloca_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_alloca_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_long_alloca_13_bad();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_declare_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_long_declare_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_declare_13_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_long_declare_13_bad();
#endif /* OMITBAD */

	return 0;

} 
