/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE127_Buffer_Underread__char_alloca_cpy_01_good();");
	CWE127_Buffer_Underread__char_alloca_cpy_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_loop_01_good();");
	CWE127_Buffer_Underread__char_alloca_loop_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_memcpy_01_good();");
	CWE127_Buffer_Underread__char_alloca_memcpy_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_memmove_01_good();");
	CWE127_Buffer_Underread__char_alloca_memmove_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_ncpy_01_good();");
	CWE127_Buffer_Underread__char_alloca_ncpy_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_declare_cpy_01_good();");
	CWE127_Buffer_Underread__char_declare_cpy_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_declare_loop_01_good();");
	CWE127_Buffer_Underread__char_declare_loop_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_declare_memcpy_01_good();");
	CWE127_Buffer_Underread__char_declare_memcpy_01_good();

	printLine("Calling CWE127_Buffer_Underread__char_declare_memmove_01_good();");
	CWE127_Buffer_Underread__char_declare_memmove_01_good();


	printLine("Calling CWE127_Buffer_Underread__char_declare_ncpy_01_good();");
	CWE127_Buffer_Underread__char_declare_ncpy_01_good();


	printLine("Calling CWE127_Buffer_Underread__CWE839_connect_socket_01_good();");
	CWE127_Buffer_Underread__CWE839_connect_socket_01_good();


	printLine("Calling CWE127_Buffer_Underread__CWE839_connect_socket_22_good();");
	CWE127_Buffer_Underread__CWE839_connect_socket_22_good();


	printLine("Calling CWE127_Buffer_Underread__CWE839_fgets_01_good();");
	CWE127_Buffer_Underread__CWE839_fgets_01_good();

	printLine("Calling CWE127_Buffer_Underread__CWE839_fgets_22_good();");
	CWE127_Buffer_Underread__CWE839_fgets_22_good();


	printLine("Calling CWE127_Buffer_Underread__CWE839_fscanf_01_good();");
	CWE127_Buffer_Underread__CWE839_fscanf_01_good();


	printLine("Calling CWE127_Buffer_Underread__CWE839_fscanf_22_good();");
	CWE127_Buffer_Underread__CWE839_fscanf_22_good();

	printLine("Calling CWE127_Buffer_Underread__CWE839_listen_socket_01_good();");
	CWE127_Buffer_Underread__CWE839_listen_socket_01_good();


	printLine("Calling CWE127_Buffer_Underread__CWE839_listen_socket_22_good();");
	CWE127_Buffer_Underread__CWE839_listen_socket_22_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
		printLine("Calling CWE127_Buffer_Underread__char_alloca_cpy_01_bad();");
	CWE127_Buffer_Underread__char_alloca_cpy_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_loop_01_bad();");
	CWE127_Buffer_Underread__char_alloca_loop_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_memcpy_01_bad();");
	CWE127_Buffer_Underread__char_alloca_memcpy_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_memmove_01_bad();");
	CWE127_Buffer_Underread__char_alloca_memmove_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_alloca_ncpy_01_bad();");
	CWE127_Buffer_Underread__char_alloca_ncpy_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_declare_cpy_01_bad();");
	CWE127_Buffer_Underread__char_declare_cpy_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_declare_loop_01_bad();");
	CWE127_Buffer_Underread__char_declare_loop_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_declare_memcpy_01_bad();");
	CWE127_Buffer_Underread__char_declare_memcpy_01_bad();

	printLine("Calling CWE127_Buffer_Underread__char_declare_memmove_01_bad();");
	CWE127_Buffer_Underread__char_declare_memmove_01_bad();


	printLine("Calling CWE127_Buffer_Underread__char_declare_ncpy_01_bad();");
	CWE127_Buffer_Underread__char_declare_ncpy_01_bad();


	printLine("Calling CWE127_Buffer_Underread__CWE839_connect_socket_01_bad();");
	CWE127_Buffer_Underread__CWE839_connect_socket_01_bad();


	printLine("Calling CWE127_Buffer_Underread__CWE839_connect_socket_22_bad();");
	CWE127_Buffer_Underread__CWE839_connect_socket_22_bad();


	printLine("Calling CWE127_Buffer_Underread__CWE839_fgets_01_bad();");
	CWE127_Buffer_Underread__CWE839_fgets_01_bad();

	printLine("Calling CWE127_Buffer_Underread__CWE839_fgets_22_bad();");
	CWE127_Buffer_Underread__CWE839_fgets_22_bad();


	printLine("Calling CWE127_Buffer_Underread__CWE839_fscanf_01_bad();");
	CWE127_Buffer_Underread__CWE839_fscanf_01_bad();


	printLine("Calling CWE127_Buffer_Underread__CWE839_fscanf_22_bad();");
	CWE127_Buffer_Underread__CWE839_fscanf_22_bad();

	printLine("Calling CWE127_Buffer_Underread__CWE839_listen_socket_01_bad();");
	CWE127_Buffer_Underread__CWE839_listen_socket_01_bad();


	printLine("Calling CWE127_Buffer_Underread__CWE839_listen_socket_22_bad();");
	CWE127_Buffer_Underread__CWE839_listen_socket_22_bad();

#endif /* OMITBAD */

	return 0;

} 
