/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE563_Unused_Variable__unused_global_value_01_good();");
	CWE563_Unused_Variable__unused_global_value_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_global_variable_01_good();");
	CWE563_Unused_Variable__unused_global_variable_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_init_variable_char_01_good();");
	CWE563_Unused_Variable__unused_init_variable_char_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_int64_t_01_good();");
	CWE563_Unused_Variable__unused_init_variable_int64_t_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_int_01_good();");
	CWE563_Unused_Variable__unused_init_variable_int_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_long_01_good();");
	CWE563_Unused_Variable__unused_init_variable_long_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_struct_01_good();");
	CWE563_Unused_Variable__unused_init_variable_struct_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_wchar_t_01_good();");
	CWE563_Unused_Variable__unused_init_variable_wchar_t_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_parameter_value_01_good();");
	CWE563_Unused_Variable__unused_parameter_value_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_parameter_variable_01_good();");
	CWE563_Unused_Variable__unused_parameter_variable_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_static_global_value_01_good();");
	CWE563_Unused_Variable__unused_static_global_value_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_static_global_variable_01_good();");
	CWE563_Unused_Variable__unused_static_global_variable_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_char_01_good();");
	CWE563_Unused_Variable__unused_uninit_variable_char_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_int64_t_01_good();");
	CWE563_Unused_Variable__unused_uninit_variable_int64_t_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_int_01_good();");
	CWE563_Unused_Variable__unused_uninit_variable_int_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_long_01_good();");
	CWE563_Unused_Variable__unused_uninit_variable_long_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_struct_01_good();");
	CWE563_Unused_Variable__unused_uninit_variable_struct_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_wchar_t_01_good();");
	CWE563_Unused_Variable__unused_uninit_variable_wchar_t_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_value_char_01_good();");
	CWE563_Unused_Variable__unused_value_char_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_value_int64_t_01_good();");
	CWE563_Unused_Variable__unused_value_int64_t_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_value_int_01_good();");
	CWE563_Unused_Variable__unused_value_int_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_value_long_01_good();");
	CWE563_Unused_Variable__unused_value_long_01_good();

	printLine("Calling CWE563_Unused_Variable__unused_value_struct_01_good();");
	CWE563_Unused_Variable__unused_value_struct_01_good();


	printLine("Calling CWE563_Unused_Variable__unused_value_wchar_t_01_good();");
	CWE563_Unused_Variable__unused_value_wchar_t_01_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE563_Unused_Variable__unused_global_value_01_bad();");
	CWE563_Unused_Variable__unused_global_value_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_global_variable_01_bad();");
	CWE563_Unused_Variable__unused_global_variable_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_init_variable_char_01_bad();");
	CWE563_Unused_Variable__unused_init_variable_char_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_int64_t_01_bad();");
	CWE563_Unused_Variable__unused_init_variable_int64_t_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_int_01_bad();");
	CWE563_Unused_Variable__unused_init_variable_int_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_long_01_bad();");
	CWE563_Unused_Variable__unused_init_variable_long_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_struct_01_bad();");
	CWE563_Unused_Variable__unused_init_variable_struct_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_init_variable_wchar_t_01_bad();");
	CWE563_Unused_Variable__unused_init_variable_wchar_t_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_parameter_value_01_bad();");
	CWE563_Unused_Variable__unused_parameter_value_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_parameter_variable_01_bad();");
	CWE563_Unused_Variable__unused_parameter_variable_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_static_global_value_01_bad();");
	CWE563_Unused_Variable__unused_static_global_value_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_static_global_variable_01_bad();");
	CWE563_Unused_Variable__unused_static_global_variable_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_char_01_bad();");
	CWE563_Unused_Variable__unused_uninit_variable_char_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_int64_t_01_bad();");
	CWE563_Unused_Variable__unused_uninit_variable_int64_t_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_int_01_bad();");
	CWE563_Unused_Variable__unused_uninit_variable_int_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_long_01_bad();");
	CWE563_Unused_Variable__unused_uninit_variable_long_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_struct_01_bad();");
	CWE563_Unused_Variable__unused_uninit_variable_struct_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_uninit_variable_wchar_t_01_bad();");
	CWE563_Unused_Variable__unused_uninit_variable_wchar_t_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_value_char_01_bad();");
	CWE563_Unused_Variable__unused_value_char_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_value_int64_t_01_bad();");
	CWE563_Unused_Variable__unused_value_int64_t_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_value_int_01_bad();");
	CWE563_Unused_Variable__unused_value_int_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_value_long_01_bad();");
	CWE563_Unused_Variable__unused_value_long_01_bad();

	printLine("Calling CWE563_Unused_Variable__unused_value_struct_01_bad();");
	CWE563_Unused_Variable__unused_value_struct_01_bad();


	printLine("Calling CWE563_Unused_Variable__unused_value_wchar_t_01_bad();");
	CWE563_Unused_Variable__unused_value_wchar_t_01_bad();
#endif /* OMITBAD */

	return 0;

} 
