/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_01_good();");
	CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_01_good();


	printLine("Calling CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_10_good();");
	CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_10_good();


	printLine("Calling CWE468_Incorrect_Pointer_Scaling__int_01_good();");
	CWE468_Incorrect_Pointer_Scaling__int_01_good();


	printLine("Calling CWE468_Incorrect_Pointer_Scaling__int_10_good();");
	CWE468_Incorrect_Pointer_Scaling__int_10_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_01_bad();");
	CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_01_bad();

	printLine("Calling CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_10_bad();");
	CWE468_Incorrect_Pointer_Scaling__char_ptr_to_int_10_bad();


	printLine("Calling CWE468_Incorrect_Pointer_Scaling__int_01_bad();");
	CWE468_Incorrect_Pointer_Scaling__int_01_bad();


	printLine("Calling CWE468_Incorrect_Pointer_Scaling__int_10_bad();");
	CWE468_Incorrect_Pointer_Scaling__int_10_bad();


	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */



#endif /* OMITBAD */

	return 0;

} 
