/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_01_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_02_good();");
	CWE476_NULL_Pointer_Dereference__binary_if_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__char_01_good();");
	CWE476_NULL_Pointer_Dereference__char_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_02_good();");
	CWE476_NULL_Pointer_Dereference__char_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_01_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_02_good();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_01_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_02_good();");
	CWE476_NULL_Pointer_Dereference__int64_t_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__int_01_good();");
	CWE476_NULL_Pointer_Dereference__int_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_02_good();");
	CWE476_NULL_Pointer_Dereference__int_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__long_01_good();");
	CWE476_NULL_Pointer_Dereference__long_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_02_good();");
	CWE476_NULL_Pointer_Dereference__long_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_good();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_01_good();");
	CWE476_NULL_Pointer_Dereference__struct_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_02_good();");
	CWE476_NULL_Pointer_Dereference__struct_02_good();


	printLine("Calling CWE476_NULL_Pointer_Dereference__wchar_t_01_good();");
	CWE476_NULL_Pointer_Dereference__wchar_t_01_good();

	printLine("Calling CWE476_NULL_Pointer_Dereference__wchar_t_02_good();");
	CWE476_NULL_Pointer_Dereference__wchar_t_02_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_01_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__binary_if_02_bad();");
	CWE476_NULL_Pointer_Dereference__binary_if_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__char_01_bad();");
	CWE476_NULL_Pointer_Dereference__char_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__char_02_bad();");
	CWE476_NULL_Pointer_Dereference__char_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_01_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__deref_after_check_02_bad();");
	CWE476_NULL_Pointer_Dereference__deref_after_check_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_01_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int64_t_02_bad();");
	CWE476_NULL_Pointer_Dereference__int64_t_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__int_01_bad();");
	CWE476_NULL_Pointer_Dereference__int_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__int_02_bad();");
	CWE476_NULL_Pointer_Dereference__int_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__long_01_bad();");
	CWE476_NULL_Pointer_Dereference__long_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__long_02_bad();");
	CWE476_NULL_Pointer_Dereference__long_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_bad();");
	CWE476_NULL_Pointer_Dereference__null_check_after_deref_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_01_bad();");
	CWE476_NULL_Pointer_Dereference__struct_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__struct_02_bad();");
	CWE476_NULL_Pointer_Dereference__struct_02_bad();


	printLine("Calling CWE476_NULL_Pointer_Dereference__wchar_t_01_bad();");
	CWE476_NULL_Pointer_Dereference__wchar_t_01_bad();

	printLine("Calling CWE476_NULL_Pointer_Dereference__wchar_t_02_bad();");
	CWE476_NULL_Pointer_Dereference__wchar_t_02_bad();
#endif /* OMITBAD */

	return 0;

} 
